import express from "express";
import { Leave } from "../models/Leave"; 

const router = express.Router();

router.post("/leave-request", async (req: express.Request, res: express.Response) => {
    const { userId, leaveTypeId, startDate, endDate, reason, status } = req.body;

    if (!userId || !leaveTypeId || !startDate || !endDate) {
        return res.status(400).json({ message: "Missing required fields" });
    }
    
    try {
        const leaveRequest = new Leave(
            undefined, // id will be generated by the database
            userId,
            leaveTypeId,
            new Date(startDate),
            new Date(endDate),
            status,
            reason
        );
        const result = await Leave.create(leaveRequest);
        res.status(201).json({ message: "Leave request created successfully", result });
    } catch (error) {
        res.status(500).json({ message: "Failed to create leave request", error });
    }
});

router.get("/leave-requests", async (req, res) => {
    try {
        const leaveRequests = await Leave.getAllLeaveRequests();
        res.status(200).json(leaveRequests);
    } catch (error) {
        res.status(500).json({ message: "Failed to fetch leave requests", error });
    }
});

export default router;
